CREATE TABLE tb_user (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(250) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    sex CHAR(1) NOT NULL,
    profile_image TEXT,
    bio VARCHAR(255) NOT NULL,
    dietaryRestrictions TEXT,
    food_preferences TEXT,
    health_issues TEXT,
    birth_date DATE NOT NULL,
    height DOUBLE PRECISION NOT NULL,
    weight DOUBLE PRECISION NOT NULL,
    activity_level VARCHAR(50) NOT NULL,
    goal_type VARCHAR(50) NOT NULL,
    email_verified BOOLEAN NOT NULL,
    verification_token TEXT,
    password_reset_token TEXT,
    password_reset_expires_at TIMESTAMP,
    failed_login_attempts INTEGER,
    last_failed_login_at TIMESTAMP,
    account_locked BOOLEAN NOT NULL,
    phone_number VARCHAR(20) UNIQUE,
    time_zone VARCHAR(50),
    daily_calories_goal INTEGER,
    training_experience VARCHAR(50) NOT NULL,
    smoker BOOLEAN NOT NULL,
    alcohol_consumption VARCHAR(50) NOT NULL,
    sleep_hours DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);
